# Generated by Django 3.0.7 on 2021-12-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktrance',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_trance_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktrance',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Category'),
        ),
        migrations.AddField(
            model_name='stock',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='max_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_max_price_supplier', to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_min_price_supplier', to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_detail_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Invoice'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='update_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_detail_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Payer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='update_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
