# Generated by Django 3.0.7 on 2021-10-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20211006_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderToBuy',
        ),
    ]
