# Generated by Django 3.0.7 on 2021-12-11 12:42

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(default='')),
                ('img', models.ImageField(null=True, upload_to=customer.models.upload_to_customer, verbose_name='Image')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
