# Generated by Django 3.0.7 on 2022-01-08 12:51

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=customer.models.upload_to_customer, verbose_name='Image'),
        ),
    ]
