# Generated by Django 3.0.7 on 2021-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nick_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
