# Generated by Django 3.0.7 on 2022-01-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_order',
            field=models.BooleanField(default=False),
        ),
    ]
