# Generated by Django 3.0.7 on 2021-12-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('consignment', '0002_auto_20211230_0054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0001_initial'),
        ('product', '0002_auto_20211230_0054'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='old_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pos.Payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.SaleChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion.Voucher'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='conignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='old_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion.PromotionPackage'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Topping'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotion.Voucher'),
        ),
        migrations.AddField(
            model_name='orderitemtopping',
            name='topping',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
            preserve_default=False,
        ),
    ]
