# Generated by Django 3.0.7 on 2022-01-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('consignment', '0002_auto_20220102_2235'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='conignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='old_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Order'),
        ),
    ]
