# Generated by Django 3.0.7 on 2021-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20211006_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='flavour_level',
            field=models.IntegerField(choices=[('0', 'non'), ('1', 'low'), ('2', 'midium'), ('3', 'very')]),
        ),
    ]
