# Generated by Django 3.0.7 on 2022-01-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20220108_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='voucher',
        ),
    ]
