# Generated by Django 3.0.7 on 2021-11-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20211114_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.IntegerField(choices=[('1', 'on cooking'), ('2', 'on delivery'), ('3', 'finish')], default='1'),
        ),
    ]
