# Generated by Django 3.0.7 on 2021-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20211123_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='desscriptions',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='flavour_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderitemtopping',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flavour_level',
            field=models.IntegerField(choices=[('0', 'none'), ('1', 'low'), ('2', 'medium'), ('3', 'very')]),
        ),
    ]
