# Generated by Django 4.0.1 on 2022-01-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_order_create_by_order_customer_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_drink',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'on serve'), (3, 'finish')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_food',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'on serve'), (3, 'finish')], default=None, null=True),
        ),
    ]
