# Generated by Django 3.0.7 on 2022-01-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20220108_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='clear_consignment',
        ),
    ]
