# Generated by Django 4.0.1 on 2022-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_order_status_drink_alter_order_status_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status_order',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'on serve'), (3, 'finish')], default=0),
        ),
    ]
