# Generated by Django 3.0.7 on 2022-01-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220108_1251'),
        ('pos', '0006_remove_orderitem_clear_consignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_address', to='customer.AddressCustomer'),
        ),
    ]
