# Generated by Django 4.0.1 on 2022-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtopping',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
