# Generated by Django 3.0.7 on 2022-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20220108_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'cash on delivery'), (2, 'credit'), (3, 'cash'), (4, 'transfer')], default=4),
        ),
    ]
