# Generated by Django 3.0.7 on 2022-01-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220109_0747'),
        ('product', '0003_remove_topping_old_product'),
        ('pos', '0011_auto_20220110_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.SaleChannel'),
            preserve_default=False,
        ),
    ]
