# Generated by Django 3.0.7 on 2022-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20220110_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spen_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
