# Generated by Django 3.0.7 on 2022-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_order_spen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_drink',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'finish')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status_food',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'finish')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'on delivery'), (3, 'finish')], default=0),
        ),
    ]
