# Generated by Django 3.0.7 on 2022-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20220110_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'on delivery'), (3, 'finish'), (4, 'void')], default=0),
        ),
    ]
