# Generated by Django 3.0.7 on 2022-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20220110_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
