# Generated by Django 3.0.7 on 2022-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
