# Generated by Django 3.0.7 on 2022-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20220111_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status_order',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'finish')], default=0),
        ),
    ]
