# Generated by Django 3.0.7 on 2022-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20220112_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_drink',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'finish')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_food',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'on cooking'), (2, 'finish')], default=None, null=True),
        ),
    ]
