# Generated by Django 3.0.7 on 2021-12-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import promotion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=100)),
                ('start_promotion_date', models.DateField()),
                ('end_promotion_date', models.DateField()),
                ('end_reward_redemption', models.DateField()),
                ('point_price', models.IntegerField()),
                ('point', models.IntegerField(default=1)),
                ('img', models.ImageField(upload_to=promotion.models.upload_to_promotion, verbose_name='Image')),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_point_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_point_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('amount_day', models.IntegerField()),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status_use', models.BooleanField(default=True)),
                ('total_amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=promotion.models.upload_to_voucher, verbose_name='Image')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_percent', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to=promotion.models.upload_to_rewards, verbose_name='Image')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField()),
                ('status_given', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_redemption, verbose_name='Image')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer')),
                ('deal_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_deal_user', to=settings.AUTH_USER_MODEL)),
                ('deliver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_deliver_user', to=settings.AUTH_USER_MODEL)),
                ('point_promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion')),
                ('rewards', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotion.Rewards')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionPackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionPackage')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer')),
                ('point_promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('point_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PointPromotion')),
                ('rewards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Rewards')),
            ],
        ),
    ]
