# Generated by Django 3.0.7 on 2022-01-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_topping_old_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionrewards',
            name='point_promotion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promotion.PointPromotion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionrewards',
            name='rewards',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promotion.Rewards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpoint',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpoint',
            name='point_promotion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtopping',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionPackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtopping',
            name='topping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionPackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointpromotion',
            name='create_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_point_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointpromotion',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_point_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='deal_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_deal_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='deliver_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_deliver_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='point_promotion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='promotion.PointPromotion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redemption',
            name='rewards',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='promotion.Rewards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewards',
            name='create_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='rewards_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewards',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='create_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
