# Generated by Django 3.0.7 on 2022-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20220118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionpackage',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
