# Generated by Django 3.0.7 on 2022-01-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20220102_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointpromotion',
            old_name='point_price',
            new_name='price_per_point',
        ),
        migrations.RemoveField(
            model_name='pointpromotion',
            name='img',
        ),
    ]
