# Generated by Django 4.0.1 on 2022-01-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.topping'),
        ),
    ]
