# Generated by Django 3.0.7 on 2022-01-16 11:03

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20220115_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehistory',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_history, verbose_name='Image'),
        ),
    ]
