# Generated by Django 3.0.7 on 2022-01-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0002_auto_20220107_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointpromotion',
            old_name='point_price',
            new_name='price_per_point',
        ),
        migrations.RenameField(
            model_name='promotionpackage',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='promotionpackage',
            old_name='status_use',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='pointpromotion',
            name='img',
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='create_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_package_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_package, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_package_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemtopping',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PackageItem'),
        ),
        migrations.AlterField(
            model_name='itemtopping',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_rewards, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_voucher, verbose_name='Image'),
        ),
    ]
