# Generated by Django 4.0.1 on 2022-01-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_alter_itemtopping_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtopping',
            name='description',
        ),
    ]
