# Generated by Django 3.0.7 on 2022-01-09 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20220109_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher',
            field=models.CharField(default='discount 5%', max_length=100),
            preserve_default=False,
        ),
    ]
