# Generated by Django 3.0.7 on 2022-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20220118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
