# Generated by Django 3.0.7 on 2022-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20220118_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionpackage',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
