# Generated by Django 3.0.7 on 2022-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20220110_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(default='code', max_length=100),
            preserve_default=False,
        ),
    ]
