# Generated by Django 4.0.1 on 2022-01-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('promotion', '0004_remove_itemtopping_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionpackage',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='promotionpackage',
            name='normal_price',
        ),
        migrations.CreateModel(
            name='PricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionpackage')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
            ],
        ),
    ]
