# Generated by Django 3.0.7 on 2022-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
