# Generated by Django 4.0.1 on 2022-01-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_remove_promotionpackage_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpromotion',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='promotion.promotionpackage'),
        ),
    ]
