# Generated by Django 3.0.7 on 2022-01-10 03:10

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_voucher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_rewards, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_voucher, verbose_name='Image'),
        ),
    ]
