# Generated by Django 4.0.1 on 2022-01-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_alter_pointpromotion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionpackage'),
        ),
    ]
