# Generated by Django 3.0.7 on 2022-01-10 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0007_auto_20220110_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionpackage',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='promotionpackage',
            old_name='status_use',
            new_name='status',
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_package_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_package_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
