# Generated by Django 3.0.7 on 2022-01-10 11:17

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_auto_20220110_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpackage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.upload_to_package, verbose_name='Image'),
        ),
    ]
