# Generated by Django 3.0.7 on 2022-01-11 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_promotionpackage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtopping',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PackageItem'),
        ),
    ]
