# Generated by Django 3.0.7 on 2022-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_auto_20220111_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
