# Generated by Django 3.0.7 on 2022-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_auto_20220111_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtopping',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
