# Generated by Django 3.0.7 on 2022-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_auto_20220112_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionrewards',
            old_name='rewards',
            new_name='reward',
        ),
        migrations.RenameField(
            model_name='rewards',
            old_name='amount',
            new_name='point',
        ),
        migrations.AddField(
            model_name='rewards',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewards',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
