# Generated by Django 3.0.7 on 2022-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_auto_20220113_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='is_pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
