# Generated by Django 3.0.7 on 2021-12-12 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import raw_material.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('remain', models.IntegerField()),
                ('minimum', models.IntegerField(default=1)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('in_refrigerator', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(default='raw_material/default.jpg', upload_to=raw_material.models.upload_to_raw_material, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.IntegerField()),
                ('payment', models.CharField(choices=[('cash', 'จ่ายสด'), ('transfer', 'โอน')], max_length=8)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('descriptions', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(default='supplier/default.jpg', upload_to=raw_material.models.upload_to_supplier, verbose_name='Image')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptRawMaterialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('remark', models.TextField(blank=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_detail_create_by', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
                ('receipt_raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.ReceiptRawMaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_detail_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='receiptrawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='receiptrawmaterial',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterialCategory'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='max_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_max_price_supplier', to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='min_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_min_price_supplier', to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PickUpRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up_raw_material_create_by', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
            ],
        ),
    ]
