# Generated by Django 3.0.7 on 2021-12-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import raw_material.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='max_price_supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='min_price_supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_l',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_m',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_s',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='l_to_m',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='m_to_s',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='maximum',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_l',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_l', to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_m',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_m', to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_s',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_s', to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='google_map',
            field=models.URLField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=raw_material.models.upload_to_raw_material, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='MultiUnit',
        ),
        migrations.AddField(
            model_name='op',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial'),
        ),
        migrations.AddField(
            model_name='op',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='op',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
        ),
    ]
