# Generated by Django 3.0.7 on 2021-12-11 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrawmaterialdetail',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_detail_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrawmaterialdetail',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial'),
        ),
        migrations.AddField(
            model_name='receiptrawmaterialdetail',
            name='receipt_raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.ReceiptRawMaterial'),
        ),
        migrations.AddField(
            model_name='receiptrawmaterialdetail',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='receiptrawmaterialdetail',
            name='update_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_detail_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrawmaterial',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptrawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='receiptrawmaterial',
            name='update_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_raw_material_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterialCategory'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='max_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_max_price_supplier', to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='min_price_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_min_price_supplier', to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprawmaterial',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up_raw_material_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprawmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial'),
        ),
    ]
