# Generated by Django 3.0.7 on 2021-12-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_amount', models.IntegerField(default=1)),
                ('raw_material', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
                ('to_unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multi_unit_to_unit', to='raw_material.Unit')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multi_unit_unit', to='raw_material.Unit')),
            ],
        ),
    ]
