# Generated by Django 3.0.7 on 2021-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='maximum',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
