# Generated by Django 3.0.7 on 2021-12-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0002_auto_20211223_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='l_to_m',
            new_name='m_to_l',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='m_to_s',
            new_name='s_to_m',
        ),
        migrations.AddField(
            model_name='pickuprawmaterial',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='google_map',
            field=models.URLField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.DeleteModel(
            name='OP',
        ),
        migrations.AddField(
            model_name='po',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial'),
        ),
        migrations.AddField(
            model_name='po',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier'),
        ),
        migrations.AddField(
            model_name='po',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
        ),
    ]
