# Generated by Django 3.0.7 on 2021-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_auto_20211223_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='supplier',
            name='google_map',
            field=models.URLField(default='', max_length=400),
        ),
    ]
