# Generated by Django 4.0.1 on 2022-01-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerawmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raw_material.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
