# Generated by Django 3.0.7 on 2021-12-20 12:19

from django.db import migrations, models
import django.db.models.deletion
import raw_material.models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_auto_20211219_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='img',
            field=models.ImageField(default=None, upload_to=raw_material.models.upload_to_raw_material, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
            ],
        ),
    ]
