# Generated by Django 3.0.7 on 2021-12-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20211229_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
