# Generated by Django 3.0.7 on 2021-12-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20211220_1919'),
        ('raw_material', '0003_auto_20211220_1038'),
    ]

    operations = [
    ]
