# Generated by Django 3.0.7 on 2021-12-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20211223_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
