# Generated by Django 3.0.7 on 2021-12-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20211223_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='l_to_m',
            new_name='m_to_l',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='m_to_s',
            new_name='s_to_m',
        ),
    ]
