# Generated by Django 3.0.7 on 2021-12-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20211223_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='descriptions',
        ),
    ]
