# Generated by Django 3.0.7 on 2021-12-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_merge_20211221_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='max_price_supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='min_price_supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
    ]
