# Generated by Django 4.0.1 on 2022-01-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_alter_pickuprawmaterial_id_alter_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
