# Generated by Django 3.0.7 on 2021-12-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_auto_20211223_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprawmaterial',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
            preserve_default=False,
        ),
    ]
