# Generated by Django 3.0.7 on 2021-12-23 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0004_op_last_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OP',
            new_name='PO',
        ),
    ]
