# Generated by Django 3.0.7 on 2021-12-24 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0005_pickuprawmaterial_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
            ],
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='remark',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='OP',
        ),
    ]
