# Generated by Django 3.0.7 on 2021-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_rawmaterial_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiunit',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiunit',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiunit',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='receiptrawmaterialdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
