# Generated by Django 3.0.7 on 2021-12-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_auto_20211221_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('raw_material', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_material.RawMaterial')),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
            ],
        ),
    ]
