# Generated by Django 3.0.7 on 2021-12-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_priceunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiunit',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='multiunit',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='multiunit',
            name='min_price',
        ),
    ]
