# Generated by Django 3.0.7 on 2021-12-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_auto_20211222_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceunit',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='priceunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='avg_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='l_to_m',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='m_to_s',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_l',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_l', to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_m',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_m', to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_s',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_unit_s', to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MultiUnit',
        ),
        migrations.DeleteModel(
            name='PriceUnit',
        ),
    ]
