# Generated by Django 3.0.7 on 2021-12-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
