# Generated by Django 3.0.7 on 2021-12-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
