# Generated by Django 3.0.7 on 2021-12-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('customer', models.BooleanField(default=False)),
                ('material', models.BooleanField(default=False)),
                ('pos', models.BooleanField(default=False)),
                ('product', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('raw_material', models.BooleanField(default=False)),
                ('user', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bartender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_chef',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_purchaser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_service',
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
