# Generated by Django 3.0.7 on 2021-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211218_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_working',
            field=models.IntegerField(choices=[(0, 'not working'), (1, 'working'), (2, 'banned')], default=1),
        ),
    ]
