# Generated by Django 3.0.7 on 2021-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211213_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_working',
            field=models.BooleanField(choices=[('0', 'not working'), ('1', 'working'), ('2', 'banned')], default='1'),
        ),
    ]
