# Generated by Django 3.0.7 on 2021-12-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='token',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='time_login',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
