# Generated by Django 3.0.7 on 2021-12-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211216_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_working',
            field=models.IntegerField(choices=[('0', 'not working'), ('1', 'working'), ('2', 'banned')], default='1'),
        ),
    ]
