# Generated by Django 3.0.7 on 2021-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211216_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_bartender',
            new_name='is_barista',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_purchaser',
            new_name='is_purchesing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_service',
        ),
        migrations.AddField(
            model_name='user',
            name='is_receptionest',
            field=models.BooleanField(default=False),
        ),
    ]
