# Generated by Django 3.0.7 on 2021-12-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211216_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_receptionest',
            new_name='is_receptionist',
        ),
    ]
