# Generated by Django 3.2.7 on 2021-10-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'able'), ('0', 'disable')], default='1')),
                ('sale_channel', models.CharField(max_length=100)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_topping', models.CharField(max_length=100)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'able'), ('0', 'disable')], default='1')),
                ('name', models.CharField(max_length=50)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.topping')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'true'), ('0', 'false')], default='1')),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('1', 'able'), ('0', 'disable')], default='1')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_create_by', to=settings.AUTH_USER_MODEL)),
                ('type_topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.typetopping')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.topping')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_product_create_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
