# Generated by Django 3.0.7 on 2022-01-16 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_category_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_category_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=product.models.upload_to_topping, verbose_name='Image')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2)),
                ('remain', models.IntegerField(default=0)),
                ('type_topping', models.IntegerField(choices=[(3, 'ของคาว'), (2, 'ของหวาน'), (1, 'ขนม')])),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=None, null=True)),
                ('warehouse', models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ToppingCategory')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('img', models.ImageField(default=None, null=True, upload_to=product.models.upload_to_sale_channel, verbose_name='Image')),
                ('sale_channel', models.CharField(max_length=100)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(default=None, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type_category', models.IntegerField(choices=[(1, 'ของหวาน'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_category_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=product.models.upload_to_product, verbose_name='Image')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('flavour_level', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2)),
                ('remain', models.IntegerField(default=0)),
                ('flavour', models.IntegerField(choices=[(1, 'เผ็ด'), (2, 'หวาน')])),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=None, null=True)),
                ('type_product', models.IntegerField(choices=[(1, 'ของหวาน'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')], default=3)),
                ('warehouse', models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ProductCategory')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_create_by', to=settings.AUTH_USER_MODEL)),
                ('old_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
                ('topping_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ToppingCategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.PriceTopping')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.PriceProduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel')),
            ],
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='add_product_create_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='add_product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
