# Generated by Django 3.0.7 on 2021-12-28 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_auto_20211228_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='salechannel',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='maximum',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salechannel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salechannel',
            name='gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='update_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='add_product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavour_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=product.models.upload_to_product, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_topping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_topping',
            field=models.IntegerField(choices=[(0, 'ไม่มี toppping'), (1, 'โรตี'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0),
        ),
    ]
