# Generated by Django 3.0.7 on 2021-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salechannel',
            name='color',
        ),
        migrations.AddField(
            model_name='salechannel',
            name='gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='is_ezzone',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
