# Generated by Django 3.0.7 on 2021-12-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetopping',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_topping_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typetopping',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_topping_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topping',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topping',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabletopping',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_topping_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabletopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping'),
        ),
        migrations.AddField(
            model_name='tabletopping',
            name='type_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TypeTopping'),
        ),
        migrations.AddField(
            model_name='tabletopping',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_topping_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_channel_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='type_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.TypeTopping'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricetopping',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricetopping',
            name='sale_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel'),
        ),
        migrations.AddField(
            model_name='pricetopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping'),
        ),
        migrations.AddField(
            model_name='pricetopping',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_product_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='sale_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel'),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_product_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
