# Generated by Django 3.0.7 on 2021-11-14 11:55

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletopping',
            name='sale_channel',
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricetopping',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product/default.jpg', upload_to=product.models.upload_to_product, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tabletopping',
            name='type_topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.TypeTopping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='img',
            field=models.ImageField(default='topping/default.jpg', upload_to=product.models.upload_to_topping, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='priceproduct',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricetopping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salechannel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tabletopping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='typetopping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
