# Generated by Django 3.0.7 on 2021-12-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_auto_20211224_2037'),
        ('product', '0002_auto_20211218_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
            preserve_default=False,
        ),
    ]
