# Generated by Django 3.0.7 on 2022-01-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220102_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='old_product',
        ),
    ]
