# Generated by Django 3.0.7 on 2021-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211006_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_add',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
