# Generated by Django 3.0.7 on 2021-11-23 15:20

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211114_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salechannel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='img',
            field=models.ImageField(default='topping/default.png', upload_to=product.models.upload_to_topping, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
