# Generated by Django 3.0.7 on 2021-12-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211229_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='flavour',
        ),
        migrations.AddField(
            model_name='topping',
            name='type_topping',
            field=models.IntegerField(choices=[(3, 'ของคาว'), (2, 'ของหวาน'), (1, 'ขนม')], default=1),
            preserve_default=False,
        ),
    ]
