# Generated by Django 3.0.7 on 2021-12-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20211225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavour_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=product.models.upload_to_product, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_topping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0),
        ),
    ]
