# Generated by Django 3.0.7 on 2021-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211123_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(default='sweet', max_length=50),
            preserve_default=False,
        ),
    ]
