# Generated by Django 3.0.7 on 2021-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211029_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='img_add',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
