# Generated by Django 3.0.7 on 2021-12-31 12:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salechannel',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=product.models.upload_to_sale_channel, verbose_name='Image'),
        ),
    ]
