# Generated by Django 3.0.7 on 2021-11-30 16:40

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='salechannel',
            name='img',
            field=models.ImageField(default=1, upload_to=product.models.upload_to_sale_channel, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
