# Generated by Django 3.0.7 on 2021-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211225_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
