# Generated by Django 3.0.7 on 2021-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_consignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_topping',
            field=models.IntegerField(choices=[(0, 'ไม่มี toppping'), (1, 'โรตี'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')]),
        ),
    ]
