# Generated by Django 3.0.7 on 2021-11-30 17:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_salechannel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='salechannel',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
