# Generated by Django 3.0.7 on 2021-12-01 02:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211130_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
