# Generated by Django 3.0.7 on 2021-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211225_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_consignment',
        ),
    ]
