# Generated by Django 3.0.7 on 2021-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_is_consignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
