# Generated by Django 3.0.7 on 2021-12-01 03:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211201_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
