# Generated by Django 3.0.7 on 2021-12-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211225_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='share',
        ),
    ]
