# Generated by Django 3.0.7 on 2021-12-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='percent',
            new_name='share',
        ),
    ]
