# Generated by Django 3.0.7 on 2021-12-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20211225_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salechannel',
            name='is_ezzone',
        ),
    ]
