# Generated by Django 3.0.7 on 2021-12-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_salechannel_is_ezzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='share',
        ),
    ]
