# Generated by Django 3.0.7 on 2021-12-27 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20211227_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='salechannel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salechannel',
            name='update_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
