# Generated by Django 3.0.7 on 2021-12-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20211227_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='status',
        ),
    ]
