# Generated by Django 3.0.7 on 2021-12-28 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_auto_20211224_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0018_remove_productcategory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_topping',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='type_category',
            field=models.IntegerField(choices=[(1, 'ของหวาน'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')]),
        ),
        migrations.CreateModel(
            name='ToppingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_category_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_category_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=product.models.upload_to_product, verbose_name='Image')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2)),
                ('remain', models.IntegerField(default=0)),
                ('flavour', models.IntegerField(choices=[(1, 'ของคาว'), (2, 'ของหวาน')])),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=None, null=True)),
                ('warehouse', models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('old_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Topping')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ToppingCategory')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_create_by', to=settings.AUTH_USER_MODEL)),
                ('old_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.PriceTopping')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Topping')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_topping_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
