# Generated by Django 3.0.7 on 2021-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20211228_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceproduct',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='priceproduct',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='pricetopping',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='pricetopping',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='pricetopping',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='pricetopping',
            name='update_by',
        ),
    ]
