# Generated by Django 3.0.7 on 2021-12-27 08:51

import consignment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0002_auto_20211224_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=consignment.models.upload_to_product, verbose_name='Image')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('is_topping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('flavour_level', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2)),
                ('remain', models.IntegerField(default=0)),
                ('flavour', models.IntegerField(choices=[(1, 'เผ็ด'), (2, 'หวาน')])),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=None, null=True)),
                ('share', models.IntegerField(default=0)),
                ('type_topping', models.IntegerField(choices=[(0, 'ไม่มี toppping'), (1, 'โรตี'), (2, 'เครื่องดื่ม'), (3, 'อาหาร')])),
                ('warehouse', models.IntegerField(choices=[(0, 'ไม่ต้องตัดสต็อก'), (1, 'สินค้าพร้อมขาย'), (2, 'วัตถุดิบ')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('consignment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_create_by', to=settings.AUTH_USER_MODEL)),
                ('old_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
