<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-01-18 11:29
=======
# Generated by Django 3.0.7 on 2022-01-18 11:32
>>>>>>> 0ff6639c921e9b8d28fa538608247603083c3d0a

import consignment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_material', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('line_id', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_card', models.CharField(max_length=13)),
                ('birth_date', models.DateField()),
                ('cradit_cart', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to=consignment.models.upload_to_consignment, verbose_name='Image')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'สินค้าหมด'), (1, 'สินค้าเกือบหมด'), (2, 'สินค้าพร้อมขาย')], default=2)),
                ('remain', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=None, null=True)),
                ('share', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('consignment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.consigner')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_create_by', to=settings.AUTH_USER_MODEL)),
                ('old_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.consignmentproduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.unit')),
                ('update_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignment.consignmentproduct')),
                ('sale_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.salechannel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignment.consignmentproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AddConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignment.consignmentproduct')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
