# Generated by Django 3.0.7 on 2021-12-29 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0002_auto_20211230_0054'),
        ('product', '0002_auto_20211230_0054'),
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='consignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='update_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignmentpayment',
            name='consignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='consignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.Consigner'),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='old_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceconsignment',
            name='sale_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel'),
            preserve_default=False,
        ),
    ]
