# Generated by Django 3.0.7 on 2022-01-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consignment', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceconsignment',
            name='sale_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SaleChannel'),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='consignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.Consigner'),
        ),
    ]
