# Generated by Django 3.0.7 on 2022-01-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consignment', '0002_auto_20220118_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentproduct',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='old_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raw_material.Unit'),
        ),
        migrations.AddField(
            model_name='consignmentproduct',
            name='update_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_product_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignmentpayment',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consignment.ConsignmentProduct'),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='update_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='add_consignment_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
